name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ./r-libs

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Make R lib folder if it doesn't exist
        run: mkdir -p ${{ env.R_LIBS_USER }}

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache-r
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/survey/DESCRIPTION') }}

      - name: Install R packages
        shell: Rscript {0}
        run: install.packages("survey")
        if: steps.cache-r.outputs.cache-hit != 'true'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          echo "PIP_CACHE_DIR=$(python -m pip cache dir)" >> $GITHUB_ENV

      - name: Cache python dependencies
        uses: actions/cache@v2
        id: cache-python
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt', 'requirements/requirements-dev.txt') }}

      - name: Install Dependencies (uses the cache when requirements did not change)
        run: |
          python -m pip install -r requirements/requirements.txt
          python -m pip install -r requirements/requirements-dev.txt

      - name: Code Quality
        run: python -m black . --check

      - name: Test with pytest
        run: python -m pytest -n 2 --cov . --cov-report=xml  --cov-config=.coveragerc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./codecov_report.gz
          verbose: true